/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppCampaignsIdRouteImport } from './routes/_app/campaigns.$id'
import { Route as AppCampaignsIdScenesSceneIdRouteImport } from './routes/_app/campaigns.$id.scenes.$sceneId'
import { Route as AppCampaignsIdCharactersNewRouteImport } from './routes/_app/campaigns.$id.characters.new'
import { Route as AppCampaignsIdCharactersCharIdRouteImport } from './routes/_app/campaigns.$id.characters.$charId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdScenesSceneIdRoute =
  AppCampaignsIdScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => AppCampaignsIdRoute,
  } as any)
const AppCampaignsIdCharactersNewRoute =
  AppCampaignsIdCharactersNewRouteImport.update({
    id: '/characters/new',
    path: '/characters/new',
    getParentRoute: () => AppCampaignsIdRoute,
  } as any)
const AppCampaignsIdCharactersCharIdRoute =
  AppCampaignsIdCharactersCharIdRouteImport.update({
    id: '/characters/$charId',
    path: '/characters/$charId',
    getParentRoute: () => AppCampaignsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/campaigns/$id': typeof AppCampaignsIdRouteWithChildren
  '/campaigns/$id/characters/$charId': typeof AppCampaignsIdCharactersCharIdRoute
  '/campaigns/$id/characters/new': typeof AppCampaignsIdCharactersNewRoute
  '/campaigns/$id/scenes/$sceneId': typeof AppCampaignsIdScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdRouteWithChildren
  '/campaigns/$id/characters/$charId': typeof AppCampaignsIdCharactersCharIdRoute
  '/campaigns/$id/characters/new': typeof AppCampaignsIdCharactersNewRoute
  '/campaigns/$id/scenes/$sceneId': typeof AppCampaignsIdScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRouteWithChildren
  '/_app/campaigns/$id/characters/$charId': typeof AppCampaignsIdCharactersCharIdRoute
  '/_app/campaigns/$id/characters/new': typeof AppCampaignsIdCharactersNewRoute
  '/_app/campaigns/$id/scenes/$sceneId': typeof AppCampaignsIdScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/$id/characters/$charId'
    | '/campaigns/$id/characters/new'
    | '/campaigns/$id/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/$id/characters/$charId'
    | '/campaigns/$id/characters/new'
    | '/campaigns/$id/scenes/$sceneId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/campaigns/$id'
    | '/_app/campaigns/$id/characters/$charId'
    | '/_app/campaigns/$id/characters/new'
    | '/_app/campaigns/$id/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id/scenes/$sceneId': {
      id: '/_app/campaigns/$id/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/campaigns/$id/scenes/$sceneId'
      preLoaderRoute: typeof AppCampaignsIdScenesSceneIdRouteImport
      parentRoute: typeof AppCampaignsIdRoute
    }
    '/_app/campaigns/$id/characters/new': {
      id: '/_app/campaigns/$id/characters/new'
      path: '/characters/new'
      fullPath: '/campaigns/$id/characters/new'
      preLoaderRoute: typeof AppCampaignsIdCharactersNewRouteImport
      parentRoute: typeof AppCampaignsIdRoute
    }
    '/_app/campaigns/$id/characters/$charId': {
      id: '/_app/campaigns/$id/characters/$charId'
      path: '/characters/$charId'
      fullPath: '/campaigns/$id/characters/$charId'
      preLoaderRoute: typeof AppCampaignsIdCharactersCharIdRouteImport
      parentRoute: typeof AppCampaignsIdRoute
    }
  }
}

interface AppCampaignsIdRouteChildren {
  AppCampaignsIdCharactersCharIdRoute: typeof AppCampaignsIdCharactersCharIdRoute
  AppCampaignsIdCharactersNewRoute: typeof AppCampaignsIdCharactersNewRoute
  AppCampaignsIdScenesSceneIdRoute: typeof AppCampaignsIdScenesSceneIdRoute
}

const AppCampaignsIdRouteChildren: AppCampaignsIdRouteChildren = {
  AppCampaignsIdCharactersCharIdRoute: AppCampaignsIdCharactersCharIdRoute,
  AppCampaignsIdCharactersNewRoute: AppCampaignsIdCharactersNewRoute,
  AppCampaignsIdScenesSceneIdRoute: AppCampaignsIdScenesSceneIdRoute,
}

const AppCampaignsIdRouteWithChildren = AppCampaignsIdRoute._addFileChildren(
  AppCampaignsIdRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsIdRoute: AppCampaignsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
